spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false?useUnicode=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
## Hibernate DDL Auto (Create, Create-drop, Update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ejb:
          interceptor: com.tehjul.gestiondestock.interceptor.Interceptor
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8881

flickr:
  apiKey:
  apiSecret: 
  appKey:
  appSecret: