services:

  database:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - db-password
    networks:
      - sql-spring
    expose:
      - 3306

  backend:
    build: api
    ports:
      - 8881:8881
    networks:
      - sql-spring
      - spring-angular
    secrets:
      - db-password
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - database

  frontend:
    build: frontend
    ports:
      - 8080:80
    networks:
      - spring-angular
    depends_on:
      - backend

volumes:
  db-data:

networks:
  sql-spring:
  spring-angular:

secrets:
  db-password:
    file: db/password.txt